import { AnySymbol } from "../Symbols/AllSymbols";

export function generateSwiftFileForAllSymbols(symbols: AnySymbol[]): string {
    let file = ''

    function text(str: string) { file += text }
    function line(str: string|undefined = undefined) { if (str) { file += `${str}\n` } else { file += '\n' } }

    line('// swiftlint:disable all')
    line('// THIS FILE IS AUTOGENERATED VIA ts-cross-mobile. DO NOT EDIT.')
    line()

    for (const symbol of symbols) {
        switch (symbol.kind) {
        case 'interface':
            const interfaceDeclaration = symbol.interfaceDecl

            line(`struct ${interfaceDeclaration.identifier} {`)

            for (const prop of interfaceDeclaration.props) {
                let type: string
                switch (prop.type.kind) {
                case 'number':
                    type = 'Double'
                    break
                case 'string':
                    type = 'String'
                    break
                case 'typeref':
                    type = prop.type.customTypeName
                    break
                }
                line(`    let ${prop.identifer}: ${type}`)                
            }

            line('}')
            line()

            break
        }
    }

    return file
}